# Generated by Django 6.0 on 2026-01-02 07:30

import core.models.account
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.account.avatar_upload_to, verbose_name='Сурет')),
                ('user_role', models.CharField(choices=[('learner', 'Оқушы'), ('teacher', 'Оқытушы'), ('admin', 'Администрация')], db_index=True, default='learner', max_length=32, verbose_name='Қолданушы рөлі')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Қолданушы',
                'verbose_name_plural': 'Қолданушылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Атауы')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='core/course/posters', verbose_name='Постер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Соңғы өзгеріс')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Қаралым')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курстар',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модульдер',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Соңғы өзгеріс')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.chapter', verbose_name='Модуль')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LessonDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('file', models.FileField(blank=True, null=True, upload_to='core/lesson/docs/', verbose_name='Файл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Сабақ құжаты',
                'verbose_name_plural': 'Сабақ құжаттары',
            },
        ),
    ]
