# Generated by Django 6.0 on 2026-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('private', 'Жабық'), ('public', 'Ашық')], default='private', max_length=32, verbose_name='Қолжетімділік'),
        ),
    ]
