# Generated by Django 6.0 on 2026-01-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(verbose_name='Атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілігі')),
            ],
            options={
                'verbose_name': 'Баған',
                'verbose_name_plural': 'Бағандар',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сұрақ')),
                ('question_type', models.CharField(choices=[('simple', 'Бір жауапты'), ('multiple', 'Көп жауапты')], default='simple', max_length=32, verbose_name='Сұрақтың түрі')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
            ],
            options={
                'verbose_name': 'Тест сұрағы',
                'verbose_name_plural': 'Тест сұрақтары',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='MatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Жауабы')),
                ('correct_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_items', to='core.matchingcolumn', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементтер',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Жауап')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Жауап',
                'verbose_name_plural': 'Жауаптар',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('video', 'Видеосабақ'), ('written', 'Жазбаша'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], default='video', max_length=32, verbose_name='Тапсырма түрі')),
                ('params', models.CharField(choices=[('none', 'Таңдалмаған'), ('Тест', [('quiz', 'Тест'), ('true-false', 'Ақиқат/жалған')]), ('Сәйкестендіру', [('row', 'Қатар'), ('col', 'Баған')])], default='none', max_length=32, verbose_name='Параметрлер')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Жалпы бағасы')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Тапсырма уақыты (мин)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.task', verbose_name='Тапсырма'),
        ),
        migrations.AddField(
            model_name='matchingcolumn',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.task', verbose_name='Тапсырма'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Фрейм URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.task', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Видеосабақ',
                'verbose_name_plural': 'Видеосабақтар',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Тапсырма')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Жазбаша',
                'verbose_name_plural': 'Жазбашалар',
            },
        ),
    ]
